function vararout = Program(varargin)
%Program Summary of this function goes here
% Делаем красивенькие кнопочки.
% глобальные параметры
global hTxtTask
global hButStart
global hButStop
global hTxtTimeInterval
global hEditTimeInterval
global hTxtVariance
global hEditVariance
global hTxtCurrent
global hTxtMin
global hTxtMinEdit
global hTxtMax
global hTxtMaxEdit
global hTxtOutCurrent

hFig = figure('Position', [400 250 550 260], 'Resize', 'off');
hTxtTask = uicontrol(hFig, 'Style', 'text', ...
                        'BackgroundColor', [0 0 0], ...
                        'ForegroundColor', [1 1 1], ...
                        'FontSize', [14], ...
                        'Position', [0 235 550 25], ...
                        'String', 'Цифровой омметр');
hButStart = uicontrol(hFig, 'Style', 'pushbutton', ...
                        'BusyAction', 'cancel', ...
                        'BackgroundColor', [0 1 0], ...
                        'ForegroundColor', [0 0 0], ...
                        'FontSize', [14], ...
                        'Position', [65 200 200 25], ...
                        'String', 'Старт', ...
                        'Callback', 'Start');
hButStop = uicontrol(hFig, 'Style', 'pushbutton', ...
                        'BackgroundColor', [1 0 0], ...
                        'ForegroundColor', [0 0 0], ...
                        'FontSize', [14], ...
                        'Position', [290 200 200 25], ...
                        'String', 'Стоп', ...
                        'Callback', 'Stop');
                    
hTxtTimeInterval = uicontrol(hFig, 'Style', 'text', ...
                        'BackgroundColor', [1 1 1], ...
                        'ForegroundColor', [0 0 0], ...
                        'FontSize', [8], ...
                        'Position', [30 150 120 15], ...
                        'String', 'Временной интервал:');
hEditTimeInterval = uicontrol(hFig, 'Style', 'edit', ...
                        'BackgroundColor', [1 1 1], ...
                        'ForegroundColor', [0 0 0], ...
                        'FontSize', [14], ...
                        'Position', [30 125 120 25], ...
                        'String', '50');
                    
hTxtVariance = uicontrol(hFig, 'Style', 'text', ...
                        'BackgroundColor', [1 1 1], ...
                        'ForegroundColor', [0 0 0], ...
                        'FontSize', [8], ...
                        'Position', [30 90 120 25], ...
                        'String', 'Максимальный разброс значений:');
hEditVariance = uicontrol(hFig, 'Style', 'edit', ...
                        'BackgroundColor', [1 1 1], ...
                        'ForegroundColor', [0 0 0], ...
                        'FontSize', [14], ...
                        'Position', [30 65 120 25], ...
                        'String', '73');
                    
hTxtCurrent = uicontrol(hFig, 'Style', 'text', ...
                        'BackgroundColor', [1 1 1], ...
                        'ForegroundColor', [0 0 0], ...
                        'FontSize', [14], ...
                        'Position', [185 150 200 25], ...
                        'String', 'Значение сопротивления:');
hTxtOutCurrent = uicontrol(hFig, 'Style', 'text', ...
                        'BackgroundColor', [1 1 1], ...
                        'ForegroundColor', [0 0 0], ...
                        'FontSize', [14], ...
                        'Position', [185 40 200 100]);

hTxtMin = uicontrol(hFig, 'Style', 'text', ...
                        'BackgroundColor', [1 1 1], ...
                        'ForegroundColor', [0 0 0], ...
                        'FontSize', [14], ...
                        'Position', [420 140 100 25], ...
                        'String', 'Min R:');
hTxtMinEdit = uicontrol(hFig, 'Style', 'text', ...
                        'BackgroundColor', [1 1 1], ...
                        'ForegroundColor', [0 0 0], ...
                        'FontSize', [14], ...
                        'Position', [420 114 100 25]);

hTxtMax = uicontrol(hFig, 'Style', 'text', ...
                        'BackgroundColor', [1 1 1], ...
                        'ForegroundColor', [0 0 0], ...
                        'FontSize', [14], ...
                        'Position', [420 80 100 25], ...
                        'String', 'Max R:');
hTxtMaxEdit = uicontrol(hFig, 'Style', 'text', ...
                        'BackgroundColor', [1 1 1], ...
                        'ForegroundColor', [0 0 0], ...
                        'FontSize', [14], ...
                        'Position', [420 54 100 25]);
end

